URL_SERVICE = "https://4bea2b1a-814c-465d-bce5-e3c55784d561.serverhub.praktikum-services.ru"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"